module.exports = {
  tableName: "purchase",
  columnNames: {
    id: "uuid",
    refCode: "ref_code",
    prCode: "pr_code",
    poCode: "po_code",
    tfCode: "tf_code",
    orCode: "or_code",
    processType: "process_type",
    prStatus: "pr_status",
    poStatus: "po_status",
    tfStatus: "tf_status",
    companyName: "company_name",
    address: "address",
    itemCount: "item_count",
    totalAmount: "total_amount",
    termsOfAgreement: "terms_of_agreement",
    purpose: "purpose",
    unit: "unit",
    attention: "attention",
    remarks: "remarks",
    requestDate: "request_date",
    orderDate: "order_date",
    orderDueDate: "order_due_date",
    transmitDate: "transmit_date",
    billingDate: "billing_date",
    receivedDate: "received_date",
    preparedDate: "prepared_date",
    preparedBy: "prepared_by",
    notedBy: "noted_by",
    receivedBy: "received_by",
    createAt: "created_at",
    updatedAt: "updated_at",
  },
};